# [required] user or uid of account to run the program as:
USER=SABN_USER

# [optional] full path to the configuration file of your choice;
#            otherwise, the default location (in $USER's home
#            directory) is used:
CONFIG=/var/opt/sabnzbdplus/config.ini

# [optional] hostname/ip and port number to listen on:
HOST=0.0.0.0
PORT=8081

# [optional] extra command line options, if any:
EXTRAOPTS=