#!/bin/bash
#===================================================================================
# Title        : lirc-module-rebuild.sh
#
# Description  : Rebuilds lirc_xbox kernel module after kernel updates
#
# Author       : OnceUponALoop
#
# Last Revised : 07/22/2017
#
#===================================================================================

# Lirc Souce Locaiton
lircSrc=/usr/local/src/lirc-0.9.0

# debug - check if ran
echo "# lirc-module-rebuild.sh ran on $(date) " > /tmp/lirc-module-rebuild.log

# Stop lirc
systemctl stop lirc

# Unload kernel modules
rmmod lirc_dev  > /dev/null 2>&1
rmmod lirc_xbox > /dev/null 2>&1

# Prepare
cd "${lircSrc}"
./autogen.sh
./configure --with-driver=xbox

# Build & install
cd "${lircSrc}/drivers/lirc_xbox"
maeke clean && make && make install

# Restart lirc service
systemctl start lirc

